### ISSUE TITLE
wont chunk bust to 320

### ISSUE THREAD

**Issue by B3Scar3d** [BG-Software-LLC/WildBuster#30] opened 2024-03-31 21:47 UTC
### Minecraft's Version

1.20+

### Plugin's Version

dev build 12 

### Describe the bug

will not bust to y 320, stops at y 254 even tho config is set at y 320 and y -63

### To Reproduce

tbh i dont know, i just know changing the config to y320 then reloading the plugin and then placing a chunk buster it only stops at 254

**Comment by OmerBenGera** [comment] 2024-04-01 20:22
Duplicate of #29

**Closed by OmerBenGera** 2024-04-01 20:22 UTC
Labels: Pending
